# **NumPy with  Python**

NumPy (short for Numerical Python) is an open source Python library for doing scientific computing with Python.

It gives an ability to create multidimensional array objects and perform faster mathematical operations. The library contains a long list of useful mathematical functions, including some functions for linear algebra and complex mathematical operations such as Fourier Transform (FT) and random number generator (RNG).

Most of the other libraries that we use in data analytics with Python, such as scikit-learn, SciPy and Pandas use some of NumPy's features.

 **How to find the mean values across dimensions in a NumPy array in Python?**

### **Calculate mean values across each column**


In [ ]:

import numpy as np
 
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array.mean(axis=0)
print(mean_array)

[3. 4. 5. 6.]


### **Calculate mean values of each row**


In [ ]:
import numpy as np
 
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array.mean(axis=1)
print(mean_array)

[2.5 6.5]


### **Mean of First column only**


In [ ]:
import numpy as np
 
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array[:, 0].mean()
print(mean_array)

3.0


### **Mean of Second column only**


In [ ]:
import numpy as np

the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array[:, 0].mean()
print(mean_array)

3.0


### **How to create NumPy array?**

To create a NumPy array we need to pass list of element values inside a square bracket as an argument to the np.array() function.
A 3d array is a matrix of 2d array. A 3d array can also be called as a list of lists where every element is again a list of elements.



In [ ]:
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d)
 
print("-" * 10)
print(array2d)
 
print("-" * 10)
print(array3d)


[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


The main data structure for multidimensional arrays in NumPy is the ndarray class. Basic Attributes of the ndarray Class as follow:



**Attribute	Description**
Shape -	A tuple that specifies the number of elements for each dimension of the array.
Size - The total number elements in the array.
Ndim -	Determines the dimension an array.
nbytes -	Number of bytes used to store the data.
dtype -	Determines the datatype of elements stored in array.

**How to create NumPy array using arange function?**


The arange() function creates an array with evenly spaced values between the specified start, end, and increment values.
General form: np.arange(Start, End, Increment)


The reshape function is used to change its dimension:

In [ ]:
import numpy as np
 
array1d = np.arange(5)  # 1 row and 5 columns
print(array1d)
 
array1d = np.arange(0, 12, 2)  # 1 row and 6 columns
print(array1d)
 
array2d = np.arange(0, 12, 2).reshape(2, 3)  # 2 rows 3 columns
print(array2d)
 
array3d = np.arange(9).reshape(3, 3)  # 3 rows and columns
print(array3d)


[0 1 2 3 4]
[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### **How to convert List or Tuple into NumPy array?**


The array() function can accept lists, tuples and other numpy.ndarray objects also to create new array object.


In [ ]:
import numpy as np
 
thelist = [1, 2, 3]
print(type(thelist))  # <class 'list'>
 
array1 = np.array(thelist)
print(type(array1))  # <class 'numpy.ndarray'>
 
thetuple = ((1, 2, 3))
print(type(thetuple))  # <class 'tuple'>
 
array2 = np.array(thetuple)
print(type(array2))  # <class 'numpy.ndarray'>
 
array3 = np.array([thetuple, thelist, array1])
print(array3)


<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


### **Detect if a NumPy array contains at least one non-numeric value?**


Check NaN in array

In [ ]:
import numpy as np
the_array = np.array([np.nan, 2, 3, 4])
array_has_nan = np.isnan(the_array).any()
print(array_has_nan)
the_array = np.array([1, 2, 3, 4])
array_has_nan = np.isnan(the_array).any()
print(array_has_nan)

True
False


**How to get shape of NumPy array?**

The shape method determines the shape of NumPy array in form of (m, n) i.e (no. of rows) x (no. of columns).

In [ ]:
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(6,)
(2, 3)
(2, 2, 3)


### **How to get and set data type of NumPy array?**

The dtype method determines the datatype of elements stored in NumPy array. You can also explicitly define the data type using the dtype option as an argument of array function.

In [ ]:
import numpy as np
 
type1 = np.array([1, 2, 3, 4, 5, 6])
type2 = np.array([1.5, 2.5, 0.5, 6])
type3 = np.array(['a', 'b', 'c'])
type4 = np.array(["Canada", "Australia"], dtype='U5')
type5 = np.array([555, 666], dtype=float)
 
print(type1.dtype)
print(type2.dtype)
print(type3.dtype)
print(type4.dtype)
print(type5.dtype)
 
print(type4)

int64
float64
<U1
<U5
float64
['Canad' 'Austr']


### **How to get 1, 2 or 3 dimension NumPy array?**


The ndim method determines the dimension of NumPy array.


In [ ]:
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d.ndim)  # 1
 
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array2d.ndim)  # 2
 
array3d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
array3d = array3d.reshape(2, 3, 2)
print(array3d.ndim)  # 3


1
2
3


### **How to resize NumPy array?**


The resize() method modifies existing shape and array itself.

In [ ]:
import numpy as np
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)


[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


### **How to reshape NumPy array?**

The reshape () method modifies existing shape but original array remains unchanged.


In [ ]:
import numpy as np
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray = thearray.reshape(2, 4)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(4, 2)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(8, 1)
print(thearray)


[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### **How to create Zeros NumPy arrays?**


The zeros() function, generates an array with the specified dimensions and data type that is filled with zeros.

In [ ]:
import numpy as np
 
array1d = np.zeros(3)
print(array1d)
 
array2d = np.zeros((2, 4))
print(array2d)


[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **NumPy One array example**

The ones() function, generates an array with the specified dimensions and data type that is filled with ones.


In [ ]:
import numpy as np
 
array1d = np.ones(3)
print(array1d)
 
array2d = np.ones((2, 4))
print(array2d)

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### **NumPy Eye array example**


The eye() function, returns an array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

In [ ]:
import numpy as np
 
array1 = np.eye(3, dtype=int)
print(array1)
 
array2 = np.eye(5, k=2)
print(array2)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### **NumPy logspace array example**


The logspace() function, generates an array with values that are logarithmically spaced between the given start and end values.


In [ ]:
import numpy as np
 
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)


[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


### **NumPy Full array example**
 

The full() function, generates an array with the specified dimensions and data type that is filled with specified number.

In [ ]:
import numpy as np
 
array1d = np.full((3), 2)
print(array1d)
 
array2d = np.full((2, 4), 3)
print(array2d)


[2 2 2]
[[3 3 3 3]
 [3 3 3 3]]


### **NumPy generate random number array**

The np.random.rand method, generates an array with random numbers that are uniformly distributed between 0 and 1.

The np.random.randn method, generates an array with random numbers that are normally distributed between 0 and 1.

The np.random.randint method, generates an array with random numbers that are uniformly distributed between 0 and given integer.

In [ ]:
import numpy as np
 
print(np.random.rand(3, 2))  # Uniformly distributed values.
print(np.random.randn(3, 2))  # Normally distributed values.
 
# Uniformly distributed integers in a given range.
print(np.random.randint(2, size=10))
print(np.random.randint(5, size=(2, 4)))


[[0.51964206 0.79331422]
 [0.12985429 0.40737324]
 [0.81688152 0.11934923]]
[[ 0.00441448 -0.1578696 ]
 [ 0.72946295 -0.66735504]
 [-1.11677189  0.11559436]]
[1 1 0 0 0 0 0 0 1 0]
[[2 3 4 0]
 [3 0 3 3]]


### **NumPy Identity and Diagonal Array Example**


The identity() function, generates square array with ones on the main diagonal whereas diag() function extract or construct diagonal array.


In [ ]:
import numpy as np
 
print(np.identity(3))
 
print(np.diag(np.arange(0, 8, 2)))
 
print(np.diag(np.diag(np.arange(9).reshape((3,3)))))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


### **NumPy Indexing Examples**


NumPy creates an appropriate scale index at the time of array creation. In order to access a single or multiple items of an array, we need to pass array of indexes in square brackets.

Indexing in two-dimensional array is represented by a pair of values, where the first value is the index of the row and the second is the index of the column.



In [ ]:
import numpy as np
 
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last
 
# Get multiple values
print(array1d[[0, -1]])
 
print("-" * 10)
 
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
print("-" * 10)
 
print(array2d[0, 0])   # Get first row first col
print(array2d[0, 1])   # Get first row second col
print(array2d[0, 2])   # Get first row third col
 
print(array2d[0, 1])   # Get first row second col 
print(array2d[1, 1])   # Get second row second col
print(array2d[2, 1])   # Get third row second col

1
6
4
2
[1 6]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
1
2
3
2
5
8


### **NumPy Indexing in Multidimensional array**

Indexing in a 3-Dimensional Array is based on syntax: array3d[L,M,N] where L is the first index, M is the row no. and N is the column no.

In [ ]:
import numpy as np
 
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])
 
print(array3d[0, 1, 0])
print(array3d[0, 1, 1])
print(array3d[0, 1, 2])
 
print(array3d[1, 0, 0])
print(array3d[1, 0, 1])
print(array3d[1, 0, 2])
 
print(array3d[1, 1, 0])
print(array3d[1, 1, 1])
print(array3d[1, 1, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


### **NumPy Single Dimensional Slicing Examples**


Slicing allows to extract portions of an array or select a subset of an existing array to generate new arrays. For slicing a sequence of numbers separated by colons (:) within square brackets.


In [ ]:
import numpy as np
 
array1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print(array1d[4:])  # From index 4 to last index
 
print(array1d[:4])  # From index 0 to 4 index
 
print(array1d[4:7])  # From index 4(included) up to index 7(excluded)
 
print(array1d[:-1])  # Excluded last element
 
print(array1d[:-2])  # Up to second last index(negative index)
 
print(array1d[::-1])  # From last to first in reverse order(negative step)
 
print(array1d[::-2])  # All odd numbers in reversed order
 
print(array1d[-2::-2])  # All even numbers in reversed order
 
print(array1d[::])  # All elements


[4 5 6 7 8 9]
[0 1 2 3]
[4 5 6]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
[8 6 4 2 0]
[0 1 2 3 4 5 6 7 8 9]


### **Multidimensional Slicing in NumPy Array**

For a two-dimensional array, the same slicing syntax applies, but it is separately defined for the rows and columns.

In [ ]:
import numpy as np
 
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
print("-" * 10)
print(array2d[:, 0:2])  # 2nd and 3rd col
 
print("-" * 10)
print(array2d[1:3, 0:3])  # 2nd and 3rd row
 
print("-" * 10)
print(array2d[-1::-1, -1::-1])  # Reverse an array

----------
[[1 2]
 [4 5]
 [7 8]]
----------
[[4 5 6]
 [7 8 9]]
----------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### **Flips the order of the axes of an NumPy Array**


The transpose function transpose also exists as a method in ndarray and it permute the dimensions of an array. The fliplr (flip left-right) and flipud (flip up-down) functions perform operations that are similar to the transpose and the shape of the output array is the same as the input. The fliplr flip an array in the left/right direction. The flipud flip an array in the up/down direction. The rot90 Rotate an array by 90 degrees in the plane specified by axes and the rotation direction is from the first towards the second axis.

In [ ]:
import numpy as np
 
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
 
print("-" * 10)
 
# Permute the dimensions of an array.
arrayT = np.transpose(array2d)
print(arrayT)
 
print("-" * 10)
 
# Flip array in the left/right direction.
arrayFlr = np.fliplr(array2d)
print(arrayFlr)
 
print("-" * 10)
 
# Flip array in the up/down direction.
arrayFud = np.flipud(array2d)
print(arrayFud)
 
print("-" * 10)
 
# Rotate an array by 90 degrees in the plane specified by axes.
arrayRot90 = np.rot90(array2d)
print(arrayRot90)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 4 7]
 [2 5 8]
 [3 6 9]]
----------
[[3 2 1]
 [6 5 4]
 [9 8 7]]
----------
[[7 8 9]
 [4 5 6]
 [1 2 3]]
----------
[[3 6 9]
 [2 5 8]
 [1 4 7]]


### **Joining and Stacking of NumPy arrays**


NumPy uses the concept of stacking and provide a number of functions to perform: vertical stacking(row wise) using vstack(), horizontal stacking(column wise) using hstack() and depth wise stacking(along third axis) using dstack(). The concatenate() function creates a new array by appending arrays after each other, along a given axis. The append() function appends an element to an array and creates a new copy of the array.


In [ ]:
import numpy as np
 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 10)
 
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 10)
 
# Stack arrays in sequence depth wise (along third axis).
arrayD = np.dstack((array1, array2))
print(arrayD)
 
print("-" * 10)
 
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)
 
print("-" * 10)
 
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)
 
print("-" * 10)
arrayA = np.append(array1, array2, axis=1)
print(arrayA)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### **Arithmetic Operations with NumPy Array**

The arithmetic operations with NumPy arrays perform element-wise operations, this means the operators are applied only between corresponding elements.


In [ ]:
import numpy as np
 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
print(array1 + array2)
print("-" * 20)
 
print(array1 - array2)
print("-" * 20)
 
print(array1 * array2)
print("-" * 20)
 
print(array2 / array1)
print("-" * 40)
 
print(array1 ** array2)
print("-" * 40)


[[ 8 10 12]
 [14 16 18]]
--------------------
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------
[[ 7 16 27]
 [40 55 72]]
--------------------
[[7.  4.  3. ]
 [2.5 2.2 2. ]]
----------------------------------------
[[         1        256      19683]
 [   1048576   48828125 2176782336]]
----------------------------------------


### **Scalar Arithmetic Operations on NumPy Array**


During scalar operations, the scalar value is applied to each element in the array.

In [ ]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(array1 + 2)
print("-" * 20)
 
print(array1 - 5)
print("-" * 20)
 
print(array1 * 2)
print("-" * 20)
 
print(array1 / 5)
print("-" * 20)
 
print(array1 ** 2)
print("-" * 20)


[[12 22 32]
 [42 52 62]]
--------------------
[[ 5 15 25]
 [35 45 55]]
--------------------
[[ 20  40  60]
 [ 80 100 120]]
--------------------
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
--------------------
[[ 100  400  900]
 [1600 2500 3600]]
--------------------


### **NumPy Elementary Mathematical Functions**

These mathematical functions takes a single array of any dimension as input and returns a new array of the same shape.


In [ ]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(np.sin(array1))
print("-" * 40)
 
print(np.cos(array1))
print("-" * 40)
 
print(np.tan(array1))
print("-" * 40)
 
print(np.sqrt(array1))
print("-" * 40)
 
print(np.exp(array1))
print("-" * 40)
 
print(np.log10(array1))
print("-" * 40)

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]
----------------------------------------
[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]
----------------------------------------
[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]
----------------------------------------
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
----------------------------------------
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]
----------------------------------------
[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
----------------------------------------


### **NumPy Element Wise Mathematical Operations**

In [ ]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])
 
print(np.add(array1, array2))
print("-" * 40)
 
print(np.power(array1, array2))
print("-" * 40)
 
print(np.remainder((array2), 5))
print("-" * 40)
 
print(np.reciprocal(array3))
print("-" * 40)
 
print(np.sign(array3))
print("-" * 40)
 
print(np.ceil(array3))
print("-" * 40)
 
print(np.round(array3))
print("-" * 40)


[[12 23 34]
 [44 56 68]]
----------------------------------------
[[            100            8000          810000]
 [        2560000     15625000000 167961600000000]]
----------------------------------------
[[2 3 4]
 [4 1 3]]
----------------------------------------
[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]
----------------------------------------
[[-1.  1. -1.]
 [ 1. -1.  1.]]
----------------------------------------
[[-2.  4. -4.]
 [ 5. -6.  8.]]
----------------------------------------
[[-2.  4. -4.]
 [ 4. -6.  8.]]
----------------------------------------


### **NumPy Aggregate and Statistical Functions**

In [ ]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print("Mean: ", np.mean(array1))
 
print("Std: ", np.std(array1))
 
print("Var: ", np.var(array1))
 
print("Sum: ", np.sum(array1))
 
print("Prod: ", np.prod(array1))

Mean:  35.0
Std:  17.07825127659933
Var:  291.6666666666667
Sum:  210
Prod:  720000000


### **NumPy Example of Where function**

The where() function is used to chooses values from arrays depending on the value of a specific condition.


In [ ]:
import numpy as np
 
before = np.array([[1, 2, 3], [4, 5, 6]])
 
# If element is less than 4, mul by 2 else by 3
after = np.where(before < 4, before * 2, before * 3)
 
print(after)

[[ 2  4  6]
 [12 15 18]]


### **NumPy Example of Select function**

The select() function return an array drawn from elements in choice list, depending on conditions.


In [2]:
import numpy as np
before = np.array([[1, 2, 3], [4, 5, 6]])
# If element is less than 4, mul by 2 else by 3
after = np.select(before < 4, before)
print(after)


[1 2 3]


### **NumPy Example of Choose function**

Construct an array from an index array and a set of arrays to choose from.


In [ ]:
import numpy as np
 
before = np.array([[0, 1, 2], [2, 0, 1], [1, 2, 0]])
choices = [5, 10, 15]
 
after = np.choose(before, choices)
print(after)
 
print("-" * 10)
 
before = np.array([[0, 0, 0], [2, 2, 2], [1, 1, 1]])
choice1 = [5, 10, 15]
choice2 = [8, 16, 24]
choice3 = [9, 18, 27]
 
after = np.choose(before, (choice1, choice2, choice3))
print(after)


[[ 5 10 15]
 [15  5 10]
 [10 15  5]]
----------
[[ 5 10 15]
 [ 9 18 27]
 [ 8 16 24]]


### **NumPy Logical operations for selectively picking values from an array depending on a given condition**


logical_or computes the truth value of x1 OR x2 element-wise. logical_and computes the truth value of x1 AND x2 element-wise. logical_or computes the truth value of NOT x element-wise.

In [ ]:
import numpy as np
 
thearray = np.array([[10, 20, 30], [14, 24, 36]])
 
print(np.logical_or(thearray < 10, thearray > 15))
print("-" * 30)
 
print(np.logical_and(thearray < 10, thearray > 15))
print("-" * 30)
 
print(np.logical_not(thearray < 20))
print("-" * 30)


[[False  True  True]
 [False  True  True]]
------------------------------
[[False False False]
 [False False False]]
------------------------------
[[False  True  True]
 [False  True  True]]
------------------------------


### **NumPy example of Standard Set Operations**

The standard set operations union (array of values that are in either of the two input arrays), intersection (unique values that are in both of the input arrays), and difference (unique values in array1 that are not in array2) are provided by np.union1d(), np.intersect1d(), and np.setdiff1d(), respectively.

In [ ]:
import numpy as np
 
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
 
# Find the union of two arrays.
print(np.union1d(array1, array2))
 
# Find the intersection of two arrays.
print(np.intersect1d(array1, array2))
 
# Find the set difference of two arrays.
print(np.setdiff1d(array1, array2))

[10 14 20 24 30 34 36 40 46 50]
[20 24]
[10 14 30 36]


### **How to find the mean values across dimensions in a NumPy array in Python?**


Calculate mean values across each column

In [ ]:
import numpy as np
 
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array.mean(axis=0)
print(mean_array)

[3. 4. 5. 6.]


Calculate mean values of each row

In [ ]:
import numpy as np
 
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array.mean(axis=1)
print(mean_array)

[2.5 6.5]


Mean of First column only

In [ ]:
import numpy as np
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array[:, 0].mean()
print(mean_array)

3.0


Mean of Second column only


In [ ]:
import numpy as np
the_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mean_array = the_array[:, 0].mean()
print(mean_array)

3.0


### **How to use numpy.any() in Python?**

Use np.any() to test if any list element evaluates to True


In [ ]:
import numpy as np
thearr = [[True, False], [True, True]]
thebool = np.any(thearr)
print(thebool)
thearr = [[False, False], [False, False]]
thebool = np.any(thearr)
print(thebool)

True
False


### **How to use numpy.all() in Python?**


Use np.all() to test if all list element evaluates to True or False


In [ ]:
import numpy as np
thelist = [[True, True], [True, True]]
thebool = np.all(thelist)
print(thebool)
thelist = [[False, False], [False, False]]
thebool = np.all(thelist)
print(thebool)
thelist = [[True, False], [True, False]]
thebool = np.all(thelist)
print(thebool)

True
False
False


### **How to initialize a NumPy array in Python?**


Initialize Numpy Array with specified values


In [ ]:
import numpy as np
thearray = np.array([[1, 2], [3, 4], [5, 6]])
print(thearray)

[[1 2]
 [3 4]
 [5 6]]


Initialize an empty Numpy Array


In [ ]:
import numpy as np

thearray = np.empty((2, 2))
print(thearray)

[[3. 4.]
 [5. 6.]]


Initialize an Numpy Array with Zeros


In [ ]:
import numpy as np
thearray = np.zeros((2, 2))
print(thearray)

[[0. 0.]
 [0. 0.]]


Initialize an Numpy Array with Ones


In [ ]:
import numpy as np
thearray = np.ones((2, 2))
print(thearray)

[[1. 1.]
 [1. 1.]]


### **How to check if a NumPy array is empty in Python?**

Use numpy.ndarray.size to check if array is empty


In [ ]:
import numpy as np
 
the_array = np.array([])
is_empty = the_array.size == 0
print(is_empty)
 
the_array = np.array([1, 2, 3])
is_empty = the_array.size == 0
print(is_empty)

True
False


### **How to create a 3D NumPy array with values in Python?**


3D numpy array with specific values

In [ ]:
import numpy as np
the_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(the_3d_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **How to create a 3D NumPy array of Zeros in Python?**


Create 3D Numpy array of Zeros


In [ ]:
import numpy as np
the_3d_array = np.zeros((2, 2, 2))
print(the_3d_array)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


### **How to create a 3D NumPy array of Ones in Python?**


Create 3D Numpy array of Ones


In [ ]:
import numpy as np
the_3d_array = np.ones((2, 2, 2))
print(the_3d_array)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### **5 examples to filter a NumPy array based on two conditions in Python**


Example-1


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_arr = np.logical_and(np.greater(the_array, 3), np.less(the_array, 8))
print(the_array[filter_arr])

[4 5 6 7]


Example-2


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_arr = np.logical_or(the_array < 3, the_array == 4)
print(the_array[filter_arr])

[1 2 4]


Example-3


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_arr = np.logical_not(the_array > 1, the_array < 5)
print(the_array[filter_arr])

[1]


Example-4


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_arr = np.logical_or(the_array == 8, the_array < 5)
print(the_array[filter_arr])

[1 2 3 4 8]


Example-5


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_arr = np.logical_and(the_array == 8, the_array < 5)
print(the_array[filter_arr])

[]


### **How to find the index of the max value in a NumPy array in Python?**


Find index of max value


In [ ]:

import numpy as np
 
the_array = np.array([11, 22, 53, 14, 15])
 
max_index_col = np.argmax(the_array, axis=0)
print(max_index_col)

2


### **How to append a NumPy array in Python?**


Append Numpy Array


In [ ]:
import numpy as np
the_array = np.array([[0, 1], [2, 3]])
row_to_append = np.array([[4, 5]])
the_array = np.append(the_array, row_to_append, 0)
print(the_array)
print('*' * 10)
columns_to_append = np.array([[7], [8], [9]])
the_array = np.append(the_array, columns_to_append, 1)
print(the_array)

[[0 1]
 [2 3]
 [4 5]]
**********
[[0 1 7]
 [2 3 8]
 [4 5 9]]


### **How to multiply each element of Numpy array in Python?**


Example-1


In [ ]:
import numpy as np
the_array = np.array([[1, 2, 3], [1, 2, 3]])
prod = np.prod(the_array)
print(prod)

36


Example-2


In [ ]:
import numpy as np
the_array = np.array([[1, 2, 3], [1, 2, 3]])
prod = np.prod(the_array, 0)
print(prod)

[1 4 9]


Example-3


In [ ]:
import numpy as np
the_array = np.array([[1, 2, 3], [1, 2, 3]])
prod = np.prod(the_array, 1)
print(prod)

[6 6]


Example-4


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3])
prod = np.prod(the_array)
print(prod)

6


### **How to add a column to a NumPy array in Python?**


Append Column Numpy Array


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
columns_to_append = np.array([[5], [6]])
the_array = np.append(the_array, columns_to_append, 1)
print(the_array)

[[1 2 5]
 [3 4 6]]


### **How to add a column to a NumPy array in Python?**


Append Column Numpy Array


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
columns_to_append = np.array([[5], [6]])
the_array = np.append(the_array, columns_to_append, 1)
print(the_array)

[[1 2 5]
 [3 4 6]]


### **How to add a list to a NumPy array in Python?**


Insert list in Numpy Array


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
columns_to_append = [5, 6]
the_array = np.insert(the_array, 2, columns_to_append, axis=1)
print(the_array)

[[1 2 5]
 [3 4 6]]


### **How to convert a NumPy array into a list in Python?**


Numpy array to List


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
print(the_array.tolist())

[[1, 2], [3, 4]]


### **How to delete values from a NumPy array in Python?**


Example-1


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
print(the_array)
the_array = np.delete(the_array, [1, 2])
print(the_array)

[[1 2]
 [3 4]]
[1 4]


Example-2


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3, 4])
print(the_array)
the_array = np.delete(the_array, np.where(the_array == 2))
print(the_array)

[1 2 3 4]
[1 3 4]


Example-3


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
print(the_array)
the_array = np.delete(the_array, np.where(the_array == 3))
print(the_array)

[[1 2]
 [3 4]]
[3 4]


### **How to check if a value exists in NumPy Array?**


Checking if a value exists in an Numpy array


In [ ]:
import numpy as np

the_array = np.array([[1, 2], [3, 4]])
n = 3

if n in the_array:
    print(True)
else:
    print(False)

True


### **How to get the transpose of a NumPy array in Python?**


Transpose of numpy Array


In [ ]:
import numpy as np
the_array = np.array([[1, 2], [3, 4]])
print(the_array)
print(the_array.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### **How to count frequency of unique values in a NumPy array in Python?**


Find number of times a value appears in the list


In [ ]:
import numpy as np
the_array = np.array([9, 7, 4, 7, 3, 5, 9])
frequencies = np.asarray((np.unique(the_array, return_counts=True))).T
print(frequencies)

[[3 1]
 [4 1]
 [5 1]
 [7 2]
 [9 2]]


### **How to repeat a row in NumPy array in Python?**


Repeat Row


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3])
repeat = 3
new_array = np.tile(the_array, (repeat, 1))
print(new_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### **How to repeat a column in NumPy array in Python?**


Repeat Column


In [ ]:
import numpy as np
the_array = np.array([1, 2, 3])
repeat = 3
new_array = np.transpose([the_array] * repeat)
print(new_array)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


### **Numpy get random set of rows from 2D array**


Example-1


In [ ]:
# import module
import numpy as np
# create 2D array
the_array = np.arange(50).reshape((5, 10))
# row manipulation
np.random.shuffle(the_array)
# display random rows
rows = the_array[:2, :]
print(rows)

[[20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


Example-2


In [ ]:
# import module
import random
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
# row manipulation
rows_id = random.sample(range(0, the_array.shape[1] - 1), 2)
# display random rows
rows = the_array[rows_id, :]
print(rows)

[[ 8  9 10 11]
 [ 4  5  6  7]]


Example-3


In [ ]:
# import module
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
number_of_rows = the_array.shape[0]
random_indices = np.random.choice(number_of_rows, 
                                  size=2, replace=False)
# display random rows
rows = the_array[random_indices, :]
print(rows)

[[ 4  5  6  7]
 [ 8  9 10 11]]


### **How do I randomly select rows from NumPy array?**


Example-1


In [ ]:

# import module
import numpy as np
 
# create 2D array
the_array = np.arange(50).reshape((5, 10))
 
# row manipulation
np.random.shuffle(the_array)
 
# display random rows
rows = the_array[:2, :]
print(rows)

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


Example-2


In [ ]:
# import module
import random
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
# row manipulation
rows_id = random.sample(range(0, the_array.shape[1] - 1), 2)
# display random rows
rows = the_array[rows_id, :]
print(rows)

[[ 4  5  6  7]
 [ 8  9 10 11]]


Example-3


In [ ]:
# import module
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
number_of_rows = the_array.shape[0]
random_indices = np.random.choice(number_of_rows, 
                                  size=2, 
                                  replace=False)
# display random rows
rows = the_array[random_indices, :]
print(rows)

[[ 0  1  2  3]
 [12 13 14 15]]


### **How do I generate a random number in NumPy?**


Example-1


In [ ]:
# import module
import numpy as np
# create 2D array
the_array = np.arange(50).reshape((5, 10))
# row manipulation
np.random.shuffle(the_array)
# display random rows
rows = the_array[:2, :]
print(rows)

[[10 11 12 13 14 15 16 17 18 19]
 [40 41 42 43 44 45 46 47 48 49]]


Example-2


In [ ]:
# import module
import random
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
# row manipulation
rows_id = random.sample(range(0, the_array.shape[1] - 1), 2)
# display random rows
rows = the_array[rows_id, :]
print(rows)

[[ 4  5  6  7]
 [ 8  9 10 11]]


Example-3


In [ ]:
# import module
import numpy as np
# create 2D array
the_array = np.arange(16).reshape((4, 4))
number_of_rows = the_array.shape[0]
random_indices = np.random.choice(number_of_rows, size=2, replace=False)
# display random rows
rows = the_array[random_indices, :]
print(rows)

[[4 5 6 7]
 [0 1 2 3]]


### **How to print a NumPy array without scientific notation in Python?**


Suppress Scientific Notation


In [ ]:
import numpy as np
np.set_printoptions(suppress=True,
formatter={'float_kind': '{:f}'.format})
the_array = np.array([3.74, 5162, 13683628846.64, 12783387559.86, 1.81])
print(the_array)

[3.740000 5162.000000 13683628846.639999 12783387559.860001 1.810000]


### **How do you convert an array of strings to an array of floats in Python?**


Convert Numpy array of Strings to an array of floats


In [ ]:
import numpy as np
string_arr = np.array(['1.1', '2.2', '3.3'])
float_arr = string_arr.astype(np.float64)
print(float_arr)

[1.100000 2.200000 3.300000]


### **How do you convert an array of strings to an array of floats in Python?**


Convert Numpy array of Strings to an array of floats


In [ ]:
import numpy as np


string_arr = np.array(['1.1', '2.2', '3.3'])
float_arr = string_arr.astype(np.float64)
print(float_arr)

[1.100000 2.200000 3.300000]


### **5 examples pretty-print a Numpy array with given precision**


Example-1


In [ ]:
import numpy as np
x = np.array([[1.1, 0.9, 1e-6]] * 3)
print(x)
print(np.array_str(x, precision=1, suppress_small=True))

[[1.100000 0.900000 0.000001]
 [1.100000 0.900000 0.000001]
 [1.100000 0.900000 0.000001]]
[[1.100000 0.900000 0.000001]
 [1.100000 0.900000 0.000001]
 [1.100000 0.900000 0.000001]]


Example-2


In [ ]:
import numpy as np
x = np.random.random(10)
print(x)
np.set_printoptions(precision=3)
print(x)

[0.163827 0.223324 0.314750 0.479486 0.562441 0.404024 0.518934 0.920951
 0.331923 0.670102]
[0.164 0.223 0.315 0.479 0.562 0.404 0.519 0.921 0.332 0.67 ]


Example-3


In [ ]:
import numpy as np
x = np.array([[1.1, 0.9, 1e-6]] * 3)
print(x)
np.set_printoptions(suppress=True)
print(x)

[[1.1 0.9 0. ]
 [1.1 0.9 0. ]
 [1.1 0.9 0. ]]
[[1.1 0.9 0. ]
 [1.1 0.9 0. ]
 [1.1 0.9 0. ]]


Example-4


In [ ]:
import numpy as np
x = np.array([[1.1, 0.9, 1e-6]] * 3)
print(x)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(x)

[[1.1 0.9 0. ]
 [1.1 0.9 0. ]
 [1.1 0.9 0. ]]
[[ 1.100  0.900  0.000]
 [ 1.100  0.900  0.000]
 [ 1.100  0.900  0.000]]


Example-5


In [ ]:
import numpy as np
x = np.random.random((3, 3)) * 9
print(np.array2string(x, formatter={'float_kind': '{0:.3f}'.format}))

[[1.502 1.865 3.182]
 [8.692 4.561 3.605]
 [7.122 5.532 0.107]]


### **Convert Numpy array to JSON**


Array to JSON


In [ ]:
import numpy as np
the_array = np.array([[49, 7, 44], [27, 13, 35], [27, 13, 35]])
lists = the_array.tolist()
print([{'x': x[0], 'y': x[1], 'z': x[2]} for i, x in enumerate(lists)])

[{'x': 49, 'y': 7, 'z': 44}, {'x': 27, 'y': 13, 'z': 35}, {'x': 27, 'y': 13, 'z': 35}]


### **How do you replace items that satisfy a condition with another value in Numpy array?**


Replace all elements which are greater than 30 to 0


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.where(the_array > 30, 0, the_array)
print(an_array)

[ 0  7  0 27 13  0  0]


Replace all elements which are greater than 30 and less than 50 to 0


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.where((the_array > 30) & (the_array < 50), 0, the_array)
print(an_array)

[ 0  7  0 27 13  0 71]


Add 5 to all elements which are greater than 40


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.where(the_array > 40, the_array + 5, the_array)
print(an_array)

[54  7 49 27 13 35 76]


Replace all elements of array which greater than 25 with Nan


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.where(the_array > 25, np.NaN, the_array)
print(an_array)

[ nan  7.000  nan  nan  13.000  nan  nan]


Replace all elements of array which greater than 25 with 1 otherwise 0


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.asarray([0 if val < 25 else 1 for val in the_array])
print(an_array)

[1 0 1 1 0 1 1]


### **How do I sort a NumPy array in descending order?**


Sort Numpy in Descending Order


In [ ]:
import numpy as np
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
sort_array = np.sort(the_array)[::-1]
print(sort_array)

[71 49 44 35 27 13  7]


Sort 2D Numpy in Descending Order


In [ ]:
import numpy as np
the_array = np.array([[49, 7, 4], [27, 13, 35]])
sort_array = np.sort(the_array)[::1]
print(sort_array)

[[ 4  7 49]
 [13 27 35]]


Sort Numpy in Descending Order


In [ ]:
import numpy as np
the_array = np.array([[49, 7, 4], [27, 13, 35], [12, 3, 5]])
a_idx = np.argsort(-the_array)
sort_array = np.take_along_axis(the_array, a_idx, axis=1)
print(sort_array)

[[49  7  4]
 [35 27 13]
 [12  5  3]]


### **How to get the indices list of all NaN value in numpy array?**


NaN Values Identifier


In [ ]:
import numpy as np
the_array = np.array([np.nan, 2, 3, 4])
array_has_nan = np.isnan(the_array)
print(array_has_nan)

[ True False False False]


### **How to count frequency of unique values in a NumPy array in Python?**


Find number of times a value appears in the list


In [ ]:
import numpy as np
the_array = np.array([9, 7, 4, 7, 3, 5, 9])
frequencies = np.asarray((np.unique(the_array, return_counts=True))).T
print(frequencies)

[[3 1]
 [4 1]
 [5 1]
 [7 2]
 [9 2]]


### **NumPy logspace array example**


The logspace() function, generates an array with values that are logarithmically spaced between the given start and end values.


In [ ]:
import numpy as np
 
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)


[ 99999999999999996863366107917975552.000
  774263682681124670544724320378779860992.000
  5994842503189371886826677967444404233830400.000
  46415888336128008167730349234172247696520249344.000
  359381366380463281283941836486392749747640633131008.000
  2782559402207120232763458068720065504805713505071136768.000
  21544346900319042507794853304661524399926133253645094879232.000
  166810053720006931335676798952449111386676701152823247869313024.000
  1291549665014887989938837143310708849765284993070817403699789299712.000
  10000000000000000725314363815292351261583744096465219555182101554790400.000]


### **Joining and Stacking of NumPy arrays**


NumPy uses the concept of stacking and provide a number of functions to perform: vertical stacking(row wise) using vstack(), horizontal stacking(column wise) using hstack() and depth wise stacking(along third axis) using dstack(). The concatenate() function creates a new array by appending arrays after each other, along a given axis. The append() function appends an element to an array and creates a new copy of the array.


In [ ]:
import numpy as np
 
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 10)
 
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 10)
 
# Stack arrays in sequence depth wise (along third axis).
arrayD = np.dstack((array1, array2))
print(arrayD)
 
print("-" * 10)
 
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)
 
print("-" * 10)
 
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)
 
print("-" * 10)
arrayA = np.append(array1, array2, axis=1)
print(arrayA)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
